server:
  port: 9999
spring:
  application:
    name: itrip-demo
  ### mail 设置
  mail:
    ### 邮箱服务器地址
    host: smtp.163.com
    ### 邮箱账号
    username: beryttl@163.com
    ### 邮箱服务器密码
    password: XOFHGIFGEPAHBVXR