spring:
  ### 允许采用 Bean 名字进行重写定义
  main:
    allow-bean-definition-overriding: true
### Eureka Client 配置信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:13131/eureka/
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000